"""empty message

Revision ID: 05052e2267c3
Revises: 68180c444558
Create Date: 2023-11-22 23:49:48.723692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05052e2267c3'
down_revision = '68180c444558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_token')

    # ### end Alembic commands ###
