"""empty message

Revision ID: 097fe7911a3c
Revises: 15160385a291
Create Date: 2023-11-22 14:55:34.152612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097fe7911a3c'
down_revision = '15160385a291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
