"""empty message

Revision ID: 15160385a291
Revises: e5bab448f582
Create Date: 2023-11-18 12:48:21.381800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15160385a291'
down_revision = 'e5bab448f582'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataforms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('firstname2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('id_number2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gender2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone_number2', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataforms', schema=None) as batch_op:
        batch_op.drop_column('phone_number2')
        batch_op.drop_column('email2')
        batch_op.drop_column('date_of_birth2')
        batch_op.drop_column('gender2')
        batch_op.drop_column('id_number2')
        batch_op.drop_column('firstname2')
        batch_op.drop_column('lastname2')

    # ### end Alembic commands ###
