"""empty message

Revision ID: 49401041bd3c
Revises: e8e452efd5cb
Create Date: 2023-11-18 08:59:12.992380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49401041bd3c'
down_revision = 'e8e452efd5cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###
