"""empty message

Revision ID: 68180c444558
Revises: 
Create Date: 2023-11-22 16:42:21.238079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68180c444558'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('user_type', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('dataforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('hub_name', sa.String(), nullable=True),
    sa.Column('hub_code', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('year_established', sa.Integer(), nullable=True),
    sa.Column('ownership', sa.String(), nullable=True),
    sa.Column('floor_size', sa.String(), nullable=True),
    sa.Column('facilities', sa.String(), nullable=True),
    sa.Column('input_center', sa.String(), nullable=True),
    sa.Column('type_of_building', sa.String(), nullable=True),
    sa.Column('gprs_longitude', sa.String(), nullable=True),
    sa.Column('gprs_latitude', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('id_number', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('lastname2', sa.String(), nullable=True),
    sa.Column('firstname2', sa.String(), nullable=True),
    sa.Column('id_number2', sa.Integer(), nullable=True),
    sa.Column('gender2', sa.String(), nullable=True),
    sa.Column('date_of_birth2', sa.String(), nullable=True),
    sa.Column('email2', sa.String(), nullable=True),
    sa.Column('phone_number2', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dataforms')
    op.drop_table('users')
    # ### end Alembic commands ###
