"""empty message

Revision ID: 70434aaae3d1
Revises: 49401041bd3c
Create Date: 2023-11-18 09:54:37.694305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70434aaae3d1'
down_revision = '49401041bd3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('hub_name', sa.String(), nullable=True),
    sa.Column('hub_code', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('year_established', sa.Integer(), nullable=True),
    sa.Column('ownership', sa.String(), nullable=True),
    sa.Column('floor_size', sa.String(), nullable=True),
    sa.Column('facilities', sa.String(), nullable=True),
    sa.Column('input_center', sa.String(), nullable=True),
    sa.Column('type_of_bulding', sa.String(), nullable=True),
    sa.Column('gprs_longitude', sa.String(), nullable=True),
    sa.Column('gprs_latitude', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('id_number', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dataforms')
    # ### end Alembic commands ###
