"""empty message

Revision ID: e5bab448f582
Revises: e901ccb47234
Create Date: 2023-11-18 11:15:13.498699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5bab448f582'
down_revision = 'e901ccb47234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataforms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_of_building', sa.String(), nullable=True))
        batch_op.drop_column('type_of_bulding')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataforms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_of_bulding', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('type_of_building')

    # ### end Alembic commands ###
